// fontawesome
import { library } from "@fortawesome/fontawesome-svg-core"
import { faChevronLeft } from "@fortawesome/pro-solid-svg-icons"
import {
  faHome as falHome,
  faInfoCircle as falInfoCircle,
  faInfo as falInfo,
  faThList as falThList,
  faCloud as falCloud,
  faPlusCircle,
  faMoon as fasMoon,
  faFog as fasFog,
  faWind as fasWind,
  faCloudSun as fasCloudSun,
  faCloudMoon as fasCloudMoon,
  faSnowflakes as fasSnowflakes,
  faCloudSleet as fasCloudSleet,
  faClouds as fasClouds,
  faSun as fasSun,
  faCloudRain as falCloudRain,
  faTrash as falTrash,
  faQuestionCircle,
} from "@fortawesome/pro-light-svg-icons"
import {
  faTint,
  faHome,
  faInfoCircle,
  faInfo,
  faThList,
  faCloud,
  faTrash,
  faMoon,
  faFog,
  faWind,
  faCloudSun,
  faCloudMoon,
  faSnowflakes,
  faCloudSleet,
  faClouds,
  faSun,
  faCloudRain,
  faRaindrops,
  faPlus,
  faEdit,
  faEllipsisV,
  faCheck,
} from "@fortawesome/pro-solid-svg-icons"
library.add(
  faHome,
  faInfoCircle,
  faThList,
  faCloud,
  faChevronLeft,
  faTint,
  falHome,
  falInfoCircle,
  falThList,
  falCloud,
  faTrash,
  falTrash,
  faPlus,
  faPlusCircle,
  fasMoon,
  fasFog,
  fasWind,
  fasCloudSun,
  fasCloudMoon,
  fasSnowflakes,
  fasCloudSleet,
  fasClouds,
  fasSun,
  falCloudRain,
  faMoon,
  faFog,
  faWind,
  faCloudSun,
  faCloudMoon,
  faSnowflakes,
  faCloudSleet,
  faClouds,
  faSun,
  faCloudRain,
  faRaindrops,
  faQuestionCircle,
  faInfo,
  falInfo,
  faEllipsisV,
  faEdit,
  faCheck
)
